apiv1/urls.py
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.routers import SimpleRouter

from apiv1.api_views import (
    AddCommentApiView,
    DislikeAPIView,
    DropAPIView,
    GetSectionsAPIView,
    GetSectionTopicsAPIView,
    GetTopicCommentsAPIView,
    GetUserAPIView,
    LikeAPIView,
    TopicViewSet,
    UpdateSettingsApiView,
)

router = SimpleRouter()
router.register(r"topics", TopicViewSet, basename="topics")

# domain.com/api/v1/
urlpatterns = [
    path("", include(router.urls)),
    path("topics/<int:ids>/comments/", GetTopicCommentsAPIView.as_view()),
    path("addcomment/", AddCommentApiView.as_view()),
    #
    path("sections/", GetSectionsAPIView.as_view()),
    path("sections/<str:section>/", GetSectionTopicsAPIView.as_view()),
    #
    path("user/<int:ids>/", GetUserAPIView.as_view()),
    path("reviewuser/like/<int:ids>/", LikeAPIView.as_view()),
    path("reviewuser/dislike/<int:ids>/", DislikeAPIView.as_view()),
    path("reviewuser/drop/<int:ids>/", DropAPIView.as_view()),
    path("updatesettings/", UpdateSettingsApiView.as_view()),
    #
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("schema/docs/", SpectacularSwaggerView.as_view(url_name="schema"))
]

forum/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("forum/", include("forum_app.urls")),
    path("", include("home_app.urls")),
    path("api/v1/", include("apiv1.urls")),
    re_path(r"^authorization/", include("djoser.urls.authtoken"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_app/urls.py
from django.urls import path

from home_app import views

app_name = "home_app"

# domain.com/
urlpatterns = [
    path("", views.home_view, name="home"),
    path("auth/", views.AuthView.as_view(), name="auth"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("account/<str:username>/", views.SomeUserView.as_view(), name="some_user"),
    path("account/like/<str:username>/", views.LikeView.as_view(), name="like"),
    path("account/dislike/<str:username>/", views.DislikeView.as_view(), name="dislike"),
    path("account/drop-review/<str:username>/", views.DropView.as_view(), name="drop")
]

home_app/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models

from schemora.conf import schemora_settings


def process_upload_user_avatar(instance: 'UserSettings', filename: str) -> str:
    return f"{settings.CUSTOM_USER_AVATARS_DIR}/{instance.user.pk}/{instance.user.pk}.{filename.split('.')[-1]}"


class UserSettings(models.Model):
    """ Модель настроек пользователя. """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timezone = models.CharField(max_length=30, default=schemora_settings.USER_SETTINGS.DEFAULT_USER_TIMEZONE)
    avatar = models.ImageField(upload_to=process_upload_user_avatar,
                               default=schemora_settings.USER_SETTINGS.DEFAULT_USER_AVATAR_FILENAME)
    signature = models.CharField(max_length=64, blank=True, default="")

    def __str__(self):
        return f"{self.user} settings."


class Review(models.Model):
    """ Модель отзывов на пользователей. """

    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reviewer")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    feedback = models.BooleanField(null=True)
    time_added = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.reviewer} review on {self.user}."


class UserRating(models.Model):
    """ Модель рейтинга конкретного камрада. """

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.IntegerField(default=0)

    def __str__(self):
        return f"{self.user} rating is {self.rating}."

home_app/forms.py
import os
from typing import Literal

from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import PasswordInput, TextInput

from forum.settings import BASE_DIR, CUSTOM_USER_AVATARS_DIR, MEDIA_ROOT
from schemora.settings.helpers import get_user_settings_model

UserSettings = get_user_settings_model()


def clean_custom_user_avatars_dir(user: User) -> Literal[None]:
    """ Функция для очищения папки с кастомными аватарками пользователя. Используется при обновлении аватарки. """

    path_to_avatar_dir = f"{MEDIA_ROOT}{CUSTOM_USER_AVATARS_DIR}/{user.pk}/"
    try:
        for file in os.listdir(BASE_DIR / path_to_avatar_dir):
            os.remove(os.path.join(BASE_DIR, path_to_avatar_dir, file))
    except FileNotFoundError:
        pass


class AuthForm(forms.Form):
    username = forms.CharField(max_length=25, min_length=5, widget=TextInput(attrs={
        'style': 'background-color: rgb(20, 20, 20); color: rgb(204, 204, 204)',
        "class": "form-input"
    }), label="Имя пользователя")
    password = forms.CharField(max_length=64, min_length=8, widget=PasswordInput(attrs={
        'style': 'background-color: rgb(20, 20, 20); color: rgb(204, 204, 204)',
        "class": "form-input"
    }), label="Пароль")


class UploadAvatarForm(forms.ModelForm):
    class Meta:
        model = UserSettings
        fields = ("avatar",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["avatar"].required, self.fields["avatar"].label = False, "Ваш аватар:"
        self.fields["avatar"].widget = forms.ClearableFileInput(attrs={
            'style': 'background-color: rgb(20, 20, 20); color: rgb(204, 204, 204)'
        })

    def save(self, commit=True):
        instance = super().save(commit=False)
        clean_custom_user_avatars_dir(instance.user)
        if commit:
            instance.save()
        return instance


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username", "password1", "password2")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].help_text = "Имя пользователя должно быть 5<=длина имени<=25, " \
                                            "не может состоять только из чисел."
        self.fields['password1'].help_text = "Пароль должен быть 8<=длина пароля<=64, " \
                                             "быть не простым, состоять не только из чисел."
        self.fields["password2"].help_text = "Повторите пароль."
        self.fields["username"].label = "Имя пользователя"
        self.fields["password1"].label = "Пароль"
        self.fields["password2"].label = "Подтверждение пароля"

        for field, input_ in {"username": TextInput, "password1": PasswordInput, "password2": PasswordInput}.items():
            self.fields[field].widget = input_(attrs={
                'style': 'background-color: rgb(20, 20, 20); color: rgb(204, 204, 204)'
            })

    def clean_username(self):
        username = self.cleaned_data["username"]
        if len(username) > 25 or len(username) < 5:
            raise forms.ValidationError("Имя пользователя должно быть 5<=длина имени<=25.")
        elif username.isnumeric() is True:
            raise forms.ValidationError("Имя пользователя не может состоять только из чисел.")

        return username

    def clean_password1(self):
        password1 = self.cleaned_data["password1"]
        if len(password1) > 64 or len(password1) < 8:
            raise forms.ValidationError("Пароль должен быть 8<=длина пароля<=64.")

        return password1


class ChangeSignatureForm(forms.ModelForm):
    class Meta:
        model = UserSettings
        fields = ("signature",)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["signature"].label = "Ваша подпись:"
        self.fields["signature"].widget = forms.TextInput(attrs={"placeholder": "Подпись"})
        self.fields["signature"].required = False

    def __call__(self, *args, **kwargs):
        return ChangeSignatureForm(*args, **kwargs)

home_app/views.py
from typing import Dict, Literal, Optional

from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render, reverse
from django.urls import reverse_lazy
from django.views.generic import View

from home_app.forms import AuthForm, RegisterForm
from services.home_app_utils import (
    AuthViewUtils,
    RegisterViewUtils,
    SettingsViewUtils,
    SomeUserViewUtils,
    check_flag,
    check_is_user_auth,
)
from services.home_mixins import AddReviewMixin, DropReviewMixin, get_rating_operation_error_message


def home_view(request: HttpRequest) -> HttpResponse:
    return render(request, "home/home.html")


class _ReviewOperationOnErrorMixin(View):
    """ Миксин, содержащий базовый on_erorr метод, который срабатывает при получении ошибки. """

    def on_error(self, user: User | Literal[False], error: Optional[int] = None) -> HttpResponse:
        param = f"show_error={error}" if error else "show_success=True"
        return redirect(f'{reverse("home_app:some_user", kwargs={"username": user.username})}?{param}')


class AddReviewView(_ReviewOperationOnErrorMixin, AddReviewMixin):
    def make_add_review(self, request: HttpRequest, username: str, like: Optional[bool] = True) -> HttpResponse:
        flag, user = self.add_review(request, {"username": username}, like)
        error_redirect = check_flag(self, user, flag)
        return error_redirect if error_redirect else self.on_error(user, None)


class LikeView(AddReviewView):
    def post(self, request: HttpRequest, username: str) -> HttpResponse:
        return self.make_add_review(request, username)


class DislikeView(AddReviewView):
    def post(self, request: HttpRequest, username: str) -> HttpResponse:
        return self.make_add_review(request, username, like=False)


class DropView(_ReviewOperationOnErrorMixin, DropReviewMixin):
    def post(self, request: HttpRequest, username: str) -> HttpResponse:
        flag, user = self.drop_review(request, {"username": username})
        error_redirect = check_flag(self, user, flag)
        return error_redirect if error_redirect else self.on_error(user, None)


class SomeUserView(View):
    def get(self, request: HttpRequest, username: str) -> HttpResponse:
        context = SomeUserViewUtils().some_user_view_utils(request, username)
        error_code = request.GET.get("show_error", False)
        try:
            error = {"error_message": get_rating_operation_error_message(int(error_code)) if error_code else None}
        except ValueError:
            error = {"error_message": None}
        return render(request, "home/some_user.html", context=context | error)


class AuthView(View):
    def get(self, request: HttpRequest, flag_error: Optional[bool] = False,
            form: Optional[Dict] = None) -> HttpResponse:
        if check_is_user_auth(request):
            return redirect("/")
        context = {
            "form": AuthForm(form),
            "flag_error": flag_error,
            "show_success": request.GET.get("show_success", False)
        }
        return render(request, "home/auth.html", context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        if check_is_user_auth(request):
            return redirect("/")
        return AuthViewUtils().auth_view_utils(self, request)


class LogoutView(View):
    def get(self, request: HttpRequest) -> HttpResponse:
        if check_is_user_auth(request):
            logout(request)
        return redirect(reverse("home_app:home"))


class RegisterView(View):
    def get(self, request: HttpRequest, flag: Optional[bool] = False, form: Optional[Dict] = None) -> HttpResponse:
        if check_is_user_auth(request):
            return redirect("/")
        context = {"form": RegisterForm(form), "flag": flag}
        return render(request, "home/register.html", context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        if check_is_user_auth(request):
            return redirect("/")
        return RegisterViewUtils().register_view_utils(self, request)


class SettingsView(LoginRequiredMixin, View):
    login_url = reverse_lazy("home_app:auth")

    def get(self, request: HttpRequest, flag_success: Optional[bool] = False,
            flag_error: Optional[bool] = False) -> HttpResponse:
        context = SettingsViewUtils().settings_view_get_utils(request, flag_success, flag_error)
        return render(request, "home/settings.html", context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        return SettingsViewUtils().settings_view_post_utils(self, request)

home_app/templates/home/auth.html
{% extends 'main.html' %}

{% block title %}Авторизация{% endblock %}
{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
{%endblock%}

{% block auth %}active{% endblock %}

{% block body %}
<div align="center" class="box">
     <h1 class="text-white indent">Пожалуйста, авторизуйтесь!</h1>

     {% if flag_error %}
         <h3 class="indent text-danger">Некоторые поля указаны неверно.</h3>
     {% elif show_success %}
         <h3 class="indent text-success">Успешно.</h3>
     {% endif %}

     <br>
     <form method="POST">
         <div class="mb-3">
             {% csrf_token %}
             {% for i in form %}
                 <span class="form-label indent" style="color: rgb(255, 255, 255)">{{ i.label_tag }}</span><br>
                 <span class="indent" style="">{{ i }}</span><br><br>
             {% endfor %}
             <p></p>
             <button class="btn btn-primary indent" type="submit">Вход</button>
         </div>
     </form>
     <p class="indent"><a href="{% url 'home_app:register' %}">Нет аккаунта?</a></p>
</div>
{%endblock%}

home_app/templates/home/home.html
{% extends 'main.html' %}

{% block title %}Домашняя{% endblock %}

{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
{%endblock%}

{% block home %}active{% endblock %}

{% block body %}
<h1 class="indent" style="color: rgb(255, 255, 255)">Домашняя</h1>

{% if message %}
     <div class="bd-callout bd-callout-info">
         <h3 class="indent"><span class="text-info">Обновлено успешно.</span></h3>
     </div>
{% endif %}

<br>
<h3 class="indent text-white">Добрый день, {% firstof request.user.username 'Аноним' %}!</h3>
{%endblock%}

home_app/templates/home/register.html
{% extends 'main.html' %}

{% block title %}Регистрация{% endblock %}
{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
{%endblock%}

{% block body %}
<div align="center">
     <h1 class="text-white indent">Страница регистрации!</h1>

     {% if flag %}
         <h3 class="indent text-danger">Какие-то поля указаны неверно.</h3>
     {% endif %}

     <br>
     <form method="POST">
         <div class="mb-3">
             {% csrf_token %}
             {% for i in form %}
                 <span class="form-label indent" style="color: rgb(255, 255, 255)">{{ i.label_tag }}</span><br>
                 <span class="indent" style="background-color: rgb(20, 20, 20); color: rgb(204, 204, 204)">{{ i }}</span><br>
                 <SPAN class="indent form-text"><code>({{i.help_text}})</code></SPAN><br><br>
             {% endfor %}
             <p></p>
             <button class="btn btn-primary indent" type="submit">Регистрация</button>
         </div>
     </form>
     <p class="indent"><a href="{% url 'home_app:auth' %}">Уже есть аккаунт?</a></p>
</div>
{%endblock%}

home_app/templates/home/settings.html
{% extends 'main.html' %}

{% block title %}Настройки{% endblock %}

{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
{% endblock %}

{% block settings %}active{% endblock %}

{% block body %}
<h1 class="indent text-white">Настройки для {{request.user.username}}</h1>

{% if flag_error %}
     <div class="p-3 bg-info bg-opacity-10 border border-danger border-start-0 rounded-end indent" style="width: 30%;">
         <h3 class="indent text-danger">{{flag_error}}</h3>
     </div>
{% endif %}

<br>
<form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     <h3><label for="timezone" class="indent text-white">Временная зона UTC: </label></h3>
        <input class="form-control indent" list="datalistOptions" id="timezone" name="timezone" placeholder="Поиск временной зоны..." style="width: 30%;">
        <datalist id="datalistOptions" >
          {% for tz in tzs %}
             <option value="{{tz}}">
         {% endfor %}
        </datalist>
     {% for _, form in forms.items %}
         {% for i in form %}
             <br>
             <h3><span class="form-label indent" style="color: rgb(255, 255, 255)">{{i.label}}</span></h3>
             <span class="indent" style="color: rgb(255, 255, 255)">{{i}}</span><br>
         {% endfor %}
     {% endfor %}
     <br>
     <button type="submit" class="btn btn-primary indent">Сохранить</button>
</form>
{% endblock %}

home_app/templates/home/some_user.html
{% extends 'main.html' %}
{% load tz %}

{% block title %}{{user.username}}{% endblock %}
{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
{%endblock%}

{% block user %}{{show_active}}{% endblock %}

{% block body %}
<h2 class="indent text-white">{{user.username}} персональная страничка!</h2>
{% if show_success %}
<div class="p-3 bg-info bg-opacity-10 border border-info border-start-0 rounded-end indent" style="width: 30%;">
     <h3 class="text-info">Обновлено успешно.</h3>
</div>
<br>
{% elif error_message %}
<div class="p-3 bg-info bg-opacity-10 border border-danger border-start-0 rounded-end indent" style="width: 30%;">
     <h3 class="indent text-danger">{{error_message}}</h3>
 </div>
<br>
{% endif %}
<div style="display: flex">
    <img src="{{MEDIA_URL}}{{image}}?{{any_random_integer}}" alt="Avatar" width="250" height="250" class="indent">
    <ul class="list-group" style="width: 100%">
         <li class="list-group-item list-group-item-secondary indent" style="width: 30%;">Дата регистрации:
              {% if tzone %}
                {% if tzone != 'Default' %}
                    {{user.date_joined|timezone:tzone|date:"H:i, d/m/Y"}}
                {% else %}
                    {{user.date_joined|date:"H:i, d/m/Y"}}
                {% endif %}
              {% else %}
                   {{user.date_joined|date:"H:i, d/m/Y"}}
              {% endif %}
         </li >
         <li class="list-group-item list-group-item-secondary indent" style="width: 30%;">Дата последнего входа:
              {% if tzone %}
                {% if tzone != 'Default' %}
                    {{user.last_login|timezone:tzone|date:"H:i, d/m/Y"}}
                {% else %}
                    {{user.last_login|date:"H:i, d/m/Y"}}
                {% endif %}
              {% else %}
                   {{user.last_login|date:"H:i, d/m/Y"}}
              {% endif %}
         </li>
        <li class="list-group-item list-group-item-secondary indent" style="width: 30%;">
            Отзывов: {{reviews_count}}. Оценка: {{user_rating}}
        </li>
        {% if like %}
        <li class="list-group-item list-group-item-secondary indent" style="width: 30%;">
            Ваш отзыв: {{like}}
        </li>
        {% endif %}
        {% if user_signature %}
        <li class="list-group-item list-group-item-secondary indent" style="width: 30%;">
            Подпись: {{user_signature}}
        </li>
        {% endif %}
    </ul>
</div>
{% if form %}
    <br>
    <h5 class="text-white indent">Вы можете оценить этого камрада!</h5>
<div class="indent text-white">
    <div style="display: inline-block;">
        <form method="post" action='{% url "home_app:like" user.username %}'>
            {% csrf_token %}
            <button type="submit" class="btn btn-success">Лайк</button>
        </form>
    </div>
    <div style="display: inline-block;">
        <form method="post" action='{% url "home_app:dislike" user.username %}'>
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">Дизлайк</button>
        </form>
    </div>
    <div style="display: inline-block;">
        <form method="post" action='{% url "home_app:drop" user.username %}'>
            {% csrf_token %}
            <button type="submit" class="btn btn-primary">Сбросить</button>
        </form>
    </div>
</div>
{% endif %}
{%endblock%}