apiv1/urls.py
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.routers import SimpleRouter

from apiv1.api_views import (
    AddCommentApiView,
    DislikeAPIView,
    DropAPIView,
    GetSectionsAPIView,
    GetSectionTopicsAPIView,
    GetTopicCommentsAPIView,
    GetUserAPIView,
    LikeAPIView,
    TopicViewSet,
    UpdateSettingsApiView,
)

router = SimpleRouter()
router.register(r"topics", TopicViewSet, basename="topics")

# domain.com/api/v1/
urlpatterns = [
    path("", include(router.urls)),
    path("topics/<int:ids>/comments/", GetTopicCommentsAPIView.as_view()),
    path("addcomment/", AddCommentApiView.as_view()),
    #
    path("sections/", GetSectionsAPIView.as_view()),
    path("sections/<str:section>/", GetSectionTopicsAPIView.as_view()),
    #
    path("user/<int:ids>/", GetUserAPIView.as_view()),
    path("reviewuser/like/<int:ids>/", LikeAPIView.as_view()),
    path("reviewuser/dislike/<int:ids>/", DislikeAPIView.as_view()),
    path("reviewuser/drop/<int:ids>/", DropAPIView.as_view()),
    path("updatesettings/", UpdateSettingsApiView.as_view()),
    #
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("schema/docs/", SpectacularSwaggerView.as_view(url_name="schema"))
]

forum/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("forum/", include("forum_app.urls")),
    path("", include("home_app.urls")),
    path("api/v1/", include("apiv1.urls")),
    re_path(r"^authorization/", include("djoser.urls.authtoken"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum_app/urls.py
from django.urls import path

from forum_app import views

app_name = "forum_app"

# domain.com/forum/
urlpatterns = [
    path("", views.forum_home_view, name="home"),
    path("add-topic/", views.AddTopicView.as_view(), name="add_topic"),
    path("my-topics/", views.SomeUserTopicsView.as_view(), name="my_topics"),
    path("search/", views.search_view, name="search"),
    path("<str:section>/", views.some_section_view, name="some_section"),
    path("<str:section>/<int:ids>/", views.some_id_view, name="some_id"),
    path("<str:section>/<int:ids>/add-comment/", views.AddCommentView.as_view(), name="add_comment"),
    path("<str:section>/<int:ids>/delete/", views.DeleteTopicView.as_view(), name="delete_topic"),
]

home_app/urls.py
from django.urls import path

from home_app import views

app_name = "home_app"

# domain.com/
urlpatterns = [
    path("", views.home_view, name="home"),
    path("auth/", views.AuthView.as_view(), name="auth"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("account/<str:username>/", views.SomeUserView.as_view(), name="some_user"),
    path("account/like/<str:username>/", views.LikeView.as_view(), name="like"),
    path("account/dislike/<str:username>/", views.DislikeView.as_view(), name="dislike"),
    path("account/drop-review/<str:username>/", views.DropView.as_view(), name="drop")
]

forum_app/models.py
from os import remove
from typing import Literal

from django.conf import settings
from django.contrib.auth.models import User
from django.core.validators import MinLengthValidator
from django.db import models
from django.db.models import QuerySet
from django.db.models.fields.files import ImageFieldFile
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver
from django.urls import reverse

from forum_app.constants import Sections
from schemora.settings.helpers import get_upload_crop_path


def _delete_upload(upload: ImageFieldFile | Literal[None]) -> Literal[None]:
    if upload:
        remove(get_upload_crop_path(upload.path))
        upload.delete(False)


def get_image_link(upload: ImageFieldFile | Literal[None]) -> str | Literal[None]:
    try:
        return settings.MEDIA_URL + upload.path.split(settings.MEDIA_ROOT)[-1]
    except ValueError:
        return None


def process_topic_upload(instance: 'Topic', filename: str) -> str:
    return f"{settings.CUSTOM_TOPIC_UPLOADS_DIR}/{instance.pk}.{filename.split('.')[-1]}"


def process_comment_upload(instance: 'Comment', filename: str) -> str:
    return f"{settings.CUSTOM_COMMENT_UPLOADS_DIR}/{instance.pk}.{filename.split('.')[-1]}"


class Comment(models.Model):
    topic = models.ForeignKey('Topic', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(validators=[MinLengthValidator(5)], max_length=2048)
    upload = models.ImageField(upload_to=process_comment_upload, null=True)
    time_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("time_added",)

    def __str__(self):
        return f"{self.topic} comment by {self.author}."

    def get_upload_link(self):
        return get_image_link(self.upload)


class Topic(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="author")
    title = models.CharField(validators=[MinLengthValidator(8)], max_length=100)
    question = models.TextField(validators=[MinLengthValidator(5)], max_length=2048)
    upload = models.ImageField(upload_to=process_topic_upload, null=True)
    section = models.CharField(choices=Sections.Sections, max_length=10, default=Sections.GENERAL)
    views = models.PositiveIntegerField(default=0)
    time_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-time_added",)

    def __str__(self):
        return f"{self.author} topic about '{self.title}'"

    def get_absolute_url(self):
        return reverse("forum_app:some_id", kwargs={"ids": self.pk, "section": self.section})

    def get_upload_link(self):
        return get_image_link(self.upload)

    @property
    def comments(self) -> QuerySet[Comment]:
        return (Comment.objects.select_related("author").only
                ("author__username", "author__id", "comment", "upload", "time_added").filter(topic=self))


@receiver(pre_delete, sender=Topic)
def topic_upload_delete(sender, instance, **kwargs):
    _delete_upload(instance.upload)


@receiver(pre_delete, sender=Comment)
def comment_upload_delete(sender, instance, **kwargs):
    _delete_upload(instance.upload)

forum_app/forms.py
from django import forms
from django.core.validators import MaxLengthValidator, MinLengthValidator

from forum_app.models import Comment, Topic


class AddTopicForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["upload"].required = False
        self.fields["section"].required = False

    class Meta:
        model = Topic
        fields = ("title", "question", "upload", "section")

        labels = {
            "title": "Название",
            "question": "Вопрос",
            "section": "Раздел",
            "upload": "Вложение"
        }

        widgets = {
            "title": forms.TextInput(attrs={
                "style": "background-color: rgb(20, 20, 20); color: rgb(204, 204, 204)",
                "class": "indent"
            }),
            "question": forms.Textarea(attrs={
                "style": "background-color: rgb(20, 20, 20); color: rgb(204, 204, 204)",
                "rows": "10",
                "cols": "60",
                "class": "indent"
            }),
            "section": forms.Select(attrs={
                'style': 'width: 30%',
                "class": "form-select indent",
            }),
            "upload": forms.ClearableFileInput(attrs={
                'style': 'background-color: rgb(20, 20, 20); color: rgb(204, 204, 204)',
                "class": "indent"
            })
        }

        validators = {
            "title": [MinLengthValidator(8), MaxLengthValidator(100)],
            "question": [MinLengthValidator(5), MaxLengthValidator(2048)]
        }


class AddCommentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["upload"].required = False

    class Meta:
        model = Comment
        fields = ("comment", "upload")

        labels = {
            "comment": "Комментарий",
            "upload": "Вложение"
        }

        widgets = {
            "comment": forms.Textarea(attrs={
                "style": "background-color: rgb(20, 20, 20);"
                "color: rgb(204, 204, 204)",
                "rows": "10",
                "cols": "60"
            }),
            "upload": forms.ClearableFileInput(attrs={
                'style': 'background-color: rgb(20, 20, 20); color: rgb(204, 204, 204)'
            })
        }

        validators = {
            "comment": [MinLengthValidator(5), MaxLengthValidator(2048)]
        }

forum_app/views.py
from typing import Optional

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from forum_app.forms import AddTopicForm
from services.forum_app_utils import (
    AddCommentViewUtils,
    AddTopicViewUtils,
    DeleteTopicViewUtils,
    ForumHomeViewUtils,
    SearchViewUtils,
    SomeIdUtils,
    SomeSectionViewUtils,
    SomeUserTopicsViewUtils,
)


def forum_home_view(request: HttpRequest) -> HttpResponse:
    context = ForumHomeViewUtils().forum_home_view_utils(request)
    return render(request, "forum/home.html", context=context)


def search_view(request: HttpRequest) -> HttpResponse:
    context = SearchViewUtils().search_view_utils(request)
    return render(request, "forum/search.html", context=context)


class AddTopicView(LoginRequiredMixin, View):
    login_url = reverse_lazy("home_app:auth")

    def get(self, request: HttpRequest, flag_error: Optional[bool] = False) -> HttpResponse:
        context = {
            "form": AddTopicForm(),
            "flag_error": flag_error,
            "forum": True
        }
        return render(request, "forum/add_topic.html", context=context)

    def post(self, request: HttpRequest) -> HttpResponse:
        return AddTopicViewUtils().add_topic_view_utils(self, request)


class AddCommentView(LoginRequiredMixin, View):
    login_url = reverse_lazy("home_app:auth")

    def get(self, request: HttpRequest, section: str, ids: int, flag_error: Optional[bool] = False) -> HttpResponse:
        context = AddCommentViewUtils().add_comment_view_utils(section, ids, flag_error)
        return render(request, "forum/add_comment.html", context=context)

    def post(self, request: HttpRequest, section: str, ids: int) -> HttpResponse:
        return AddCommentViewUtils().add_comment_view_post_utils(self, request, section, ids)


def some_id_view(request: HttpRequest, section: str, ids: int) -> HttpResponse:
    context = SomeIdUtils().some_id_view_utils(request, section, ids)
    return render(request, "forum/some_id.html", context=context)


def some_section_view(request: HttpRequest, section: str) -> HttpResponse:
    context = SomeSectionViewUtils().some_section_view_utils(request, section)
    return render(request, "forum/some_header.html", context=context)


class SomeUserTopicsView(LoginRequiredMixin, View):
    login_url = reverse_lazy("home_app:auth")

    def get(self, request: HttpRequest) -> HttpResponse:
        context = SomeUserTopicsViewUtils().some_user_topics_view_utils(request)
        return render(request, "forum/some_user_topics.html", context=context)


class DeleteTopicView(LoginRequiredMixin, View):
    login_url = reverse_lazy("home_app:auth")

    def get(self, request: HttpRequest, section: str, ids: int) -> HttpResponse:
        return DeleteTopicViewUtils().delete_topic_view_utils(request, section, ids)

    def post(self, request: HttpRequest, section: str, ids: int) -> HttpResponse:
        return DeleteTopicViewUtils().delete_topic_view_post_utils(request, section, ids)

forum_app/templates/forum/delete.html
{% extends 'main.html' %}

{% block title %}Удалить тему{% endblock %}
{% block forum %}active{% endblock %}

{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
{%endblock%}

{% block delete %}active{% endblock %}

{% block body %}
<br>
<form method="POST">
    {% csrf_token %}
    <h3 class="indent" style="color: rgb(255, 255, 255)">Вы уверены, что хотите удалить '{{topic.title}}'?</h3>
    <br>
    <button type="submit" class="btn btn-danger indent">Да, уверен</button>
</form>
{%endblock%}

forum_app/templates/forum/home.html
{% extends 'main.html' %}
{% load tz %}

{% block title %}Форум{% endblock %}

{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
{%endblock%}

{% block forum %}active{% endblock %}

{% block body %}
<br>
<h1 class="indent text-white" style="text-align: center">Django Форум</h1>
<table class="table border-success table-bordered table-dark table-striped" style="margin-left: 1%; width:98%">
     <thead>
         <tr>
             <th scope="col" style="width:63%; margin:auto;">Раздел</th>
             <th scope="col" style="width:8%; text-align: center;"><span style="font-size:12.5px;">Количество тем</span></th>
             <th scope="col" style="width:11%; text-align: center;"><span style="font-size:12.5px;">Последняя тема</span></th>
             <th scope="col" style="width:11%; text-align: center;"><span style="font-size:12.5px;">Автор последней темы</span></th>
         </tr>
     </thead>
     <tbody>
         {% for section in sections %}
             <tr>
                 <td>
                     <a href="{% url 'forum_app:some_section' section.section_url_alias %}" class="alert-link"><h5 class="indent" style="line-height: 10px">{{ section.section }}</h5></a>
                 </td>
                 <td>
                     <p style="line-height: 10px; text-align: center;">{{section.all_topics_count}}</p>
                 </td>
                 <td>
                     <p style="text-align: center; line-height: 10px">
                         {% if section.last_updated_time %}
                             {% if tzone %}
                                {% if tzone != 'Default' %}
                                    {{section.last_updated_time|timezone:tzone|date:"H:i, d/m/Y"}}
                                {% else %}
                                    {{section.last_updated_time|date:"H:i, d/m/Y"}}
                                {% endif %}
                            {% else %}
                                {{section.last_updated_time|date:"H:i, d/m/Y"}}
                            {% endif %}
                         {% endif %}
                     </p>
                 </td>
                 <td>
                     <p style="text-align: center; line-height: 10px">
                         {% if section.last_updated_user %}
                            <a href="{% url 'home_app:some_user' section.last_updated_user %}">{{section.last_updated_user}}</a>
                         {% endif %}
                     </p>
                 </td>
             </tr>
         {% endfor %}
     </tbody>
</table>

{%endblock%}

forum_app/templates/forum/search.html
{% extends 'main.html' %}
{% load tz %}

{% block title %}Поиск{% endblock %}

{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
{%endblock%}

{% block forum %}active{% endblock %}

{% block body %}
<br>
<h1 class="indent text-white" style="text-align: center">Поиск</h1>
{% if search_keys %}
<h6 class="indent text-white">Найдено: {{ all_topics_count }}</h6>
{% endif %}
{% if all_topics %}
<table class="table border-success table-bordered table-dark table-striped" style="margin-left: 1%; width:98%">
     <thead>
         <tr>
             <th scope="col" style="width:60%; margin:auto;">Название</th>
             <th scope="col" style="width:15%; text-align: center;"><span style="font-size:15px;">Время добавления</span></th>
             <th scope="col" style="width:5%; text-align: center;"><span style="font-size:12.5px;">Просмотры</span></th>
             <th scope="col" style="width:20%; text-align: center;">Автор</th>
         </tr>
     </thead>
     <tbody>
         {% for topic in all_topics %}
             <tr>
                 <td>
                     <a href="{{topic.obj.get_absolute_url}}" class="alert-link"><h5 class="indent" style="line-height: 10px">{{ topic.obj.title }}
                     <span style="float:right; font-size: 15px; color:rgb(128,128,128);">
                         в {{topic.section}}
                     </span>
                     </h5></a>
                 </td>
                 <td>
                     <p style="text-align: center; line-height: 10px">
                         {% if tzone %}
                            {% if tzone != 'Default' %}
                                {{topic.obj.time_added|timezone:tzone|date:"H:i, d/m/Y"}}
                            {% else %}
                                {{topic.obj.time_added|date:"H:i, d/m/Y"}}
                            {% endif %}
                        {% else %}
                            {{topic.obj.time_added|date:"H:i, d/m/Y"}}
                        {% endif %}
                     </p>
                 </td>
                 <td>
                     <p style="line-height: 10px; text-align: center;">{{topic.obj.views}}</p>
                 </td>
                 <td>
                     <p style="text-align: center; line-height: 10px"><a href="{% url 'home_app:some_user' topic.obj.author.username %}">{{topic.obj.author.username}}</a></p>
                 </td>
             </tr>
         {% endfor %}
     </tbody>
</table>
{% else %}
<h3 class="text-white indent">Темы не надены.</h3>
{% endif %}
{%endblock%}

forum_app/templates/forum/some_header.html
{% extends 'main.html' %}
{% load tz %}

{% block title %}{{section}}{% endblock %}

{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
{%endblock%}

{% block forum %}active{% endblock %}

{% block body %}
<br>
<h1 class="indent text-white" style="text-align: center">{{section}}</h1>
{% if success_updated == 'True' %}
     <div class="p-3 bg-info bg-opacity-10 border border-info border-start-0 rounded-end indent" style="width: 30%;">
         <h3 class="text-info">Обновлено успешно.</h3>
     </div>
<br><br>
{% elif search_keys %}
    <h6 class="indent text-white">Найдено: {{ all_topics_count }}</h6>
{% else %}
<br>
{% endif %}
{% if all_topics %}
<table class="table border-success table-bordered table-dark table-striped" style="margin-left: 1%; width:98%">
     <thead>
         <tr>
             <th scope="col" style="width:60%; margin:auto;">Название</th>
             <th scope="col" style="width:15%; text-align: center;"><span style="font-size:15px;">Время добавления</span></th>
             <th scope="col" style="width:5%; text-align: center;"><span style="font-size:12.5px;">Просмотры</span></th>
             <th scope="col" style="width:20%; text-align: center;">Автор</th>
         </tr>
     </thead>
     <tbody>
         {% for topic in all_topics %}
             <tr>
                 <td>
                     <a href="{{topic.get_absolute_url}}" class="alert-link"><h5 class="indent" style="line-height: 10px">{{ topic.title }}</h5></a>
                 </td>
                 <td>
                     <p style="text-align: center; line-height: 10px">
                         {% if tzone %}
                            {% if tzone != 'Default' %}
                                {{topic.time_added|timezone:tzone|date:"H:i, d/m/Y"}}
                            {% else %}
                                {{topic.time_added|date:"H:i, d/m/Y"}}
                            {% endif %}
                        {% else %}
                            {{topic.time_added|date:"H:i, d/m/Y"}}
                        {% endif %}
                     </p>
                 </td>
                 <td>
                     <p style="line-height: 10px; text-align: center;">{{topic.views}}</p>
                 </td>
                 <td>
                     <p style="text-align: center; line-height: 10px"><a href="{% url 'home_app:some_user' topic.author.username %}">{{topic.author.username}}</a></p>
                 </td>
             </tr>
         {% endfor %}
     </tbody>
</table>
{% else %}
<h3 class="text-white indent">Темы не надены.</h3>
{% endif %}
{% endblock %}

forum_app/templates/forum/some_id.html
{% extends 'main.html' %}
{% load tz %}

{% block title %}{{ topic.obj.title }}{% endblock %}

{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
{%endblock%}
{% block forum %}active{% endblock %}

{% block body %}
<br>

<table class="table table-bordered border-light-subtle" style="margin-left: 1%; width:98%; margin-bottom: 0px;">
     <tbody>
         <tr>
             <td style="background-color: darkblue"><h4 class="indent" style="color: rgb(255, 255, 255); text-align: center;">{{ topic.obj.title }} </h4></td>
         </tr>
     </tbody>
</table>
<table class="table table-bordered border-light-subtle" style="margin-left: 1%; width:98%; margin-bottom: 0px;">
     <tbody>
         <tr style="height: 40px;">
             <td style="width:{{topic.percents_of_tds_widths.0}}" valign="middle">
                 <p style="text-align: center;">
                     <a href="{% url 'home_app:some_user' topic.obj.author.username %}">{{topic.obj.author.username}}</a>
                 </p>
             </td>
             <td class="text-white" style="width:{{topic.percents_of_tds_widths.1}}">
                 {% if tzone %}
                    {% if tzone != 'Default' %}
                        {{topic.obj.time_added|timezone:tzone|date:"H:i, d/m/Y"}}
                    {% else %}
                        {{topic.obj.time_added|date:"H:i, d/m/Y"}}
                    {% endif %}
                {% else %}
                    {{topic.obj.time_added|date:"H:i, d/m/Y"}}
                {% endif %}
                 <div style="float:right">
                     Сообщение #0
                 </div>
             </td>
             {% if topic.path_to_crop_upload %}
             <td class="text-white" style="width:{{topic.percents_of_tds_widths.2}}">
                 <p style="text-align: center;">Вложение</p>
             </td>
             {% endif %}
         </tr>
         <tr>
             <td style="width:110px; height:150px;">
                 {% if topic.path_to_author_avatar %}
                     <img src="{{MEDIA_URL}}{{topic.path_to_author_avatar}}?{{any_random_integer}}" alt="Avatar" width="175" height="175" style="display: block; margin-left: auto; margin-right: auto;">
                 {% endif %}
                 <p style="text-align: center" class="text-white">Регистрация:
                     {% if tzone %}
                        {% if tzone != 'Default' %}
                            {{topic.obj.author.date_joined|timezone:tzone|date:"H:i, d/m/Y"}}
                        {% else %}
                            {{topic.obj.author.date_joined|date:"H:i, d/m/Y"}}
                        {% endif %}
                    {% else %}
                        {{topic.obj.author.date_joined|date:"H:i, d/m/Y"}}
                    {% endif %}
                 </p>
             </td>
             <td class="text-white">
                 {% autoescape off %}
                 {{ topic.obj.question|linebreaks}}
                 {%endautoescape%}
                 {% if topic.user_signature %}
                 <hr style="color: green">
                 <span class="text-secondary">{{topic.user_signature}}</span>
                 {% endif %}
             </td>
             {% if topic.path_to_crop_upload %}
             <td align="middle">
                 <a href="{{MEDIA_URL}}{{ topic.url_to_upload }}" style="font-size: 18px">
                     <img src="{{MEDIA_URL}}{{topic.path_to_crop_upload}}?{{any_random_integer}}" width="200" height="200" style="display: block; margin-left: auto; margin-right: auto;">
                 </a>
             </td>
             {% endif %}
         </tr>
     </tbody>
</table>

{% if comments %}
     <br>
     {% for position, comment in comments.items %}
         <table class="table table-bordered border-light-subtle" style="margin-left: 1%; width:98%">
             <tbody>
                 <tr style="height: 40px;">
                     <td style="width: {{comment.percents_of_tds_widths.0}}" valign="middle"><p style="text-align: center;">
                         <a href="{% url 'home_app:some_user' comment.obj.author.username %}">{{comment.obj.author.username}}</a>
                     </p></td>
                     <td class="text-white" style="width: {{comment.percents_of_tds_widths.1}}">
                         {% if tzone %}
                            {% if tzone != 'Default' %}
                                {{comment.obj.time_added|timezone:tzone|date:"H:i, d/m/Y"}}
                            {% else %}
                                {{comment.obj.time_added|date:"H:i, d/m/Y"}}
                            {% endif %}
                        {% else %}
                            {{comment.obj.time_added|date:"H:i, d/m/Y"}}
                        {% endif %}
                         <div style="float:right">
                             Сообщение #{{position}}
                         </div>
                     </td>
                     {% if comment.url_to_upload %}
                     <td class="text-white" style="width:{{comment.percents_of_tds_widths.3}}">
                         <p style="text-align: center;">Вложение</p>
                     </td>
                     {% endif %}
                 </tr>
                 <tr>
                     <td style="width:110px; height:150px;">
                         {% if comment.path_to_author_avatar %}
                             <img src="{{MEDIA_URL}}{{comment.path_to_author_avatar}}?{{any_random_integer}}" alt="Avatar" width="175" height="175" style="display: block; margin-left: auto; margin-right: auto;">
                         {% endif %}
                         <p style="text-align: center" class="text-white">Регистация:
                             {% if tzone %}
                                {% if tzone != 'Default' %}
                                    {{comment.obj.author.date_joined|timezone:tzone|date:"H:i, d/m/Y"}}
                                {% else %}
                                    {{comment.obj.author.date_joined|date:"H:i, d/m/Y"}}
                                {% endif %}
                            {% else %}
                                {{comment.obj.author.date_joined|date:"H:i, d/m/Y"}}
                            {% endif %}
                         </p>
                     </td>
                     <td class="text-white">
                         {% autoescape off %}
                         {{ comment.obj.comment|linebreaks}}
                         {%endautoescape%}
                         {% if comment.user_signature %}
                         <hr style="color: green">
                         <span class="text-secondary">{{comment.user_signature}}</span>
                         {% endif %}
                     </td>
                     {% if comment.url_to_upload %}
                     <td align="middle">
                         <div>
                             <a href="{{MEDIA_URL}}{{ comment.url_to_upload }}" style="font-size: 18px">
                                 <img src="{{MEDIA_URL}}{{comment.path_to_crop_upload}}" width="200" height="200" style="display: block; margin-left: auto; margin-right: auto;">
                             </a>
                         </div>
                     </td>
                     {% endif %}
                 </tr>
             </tbody>
         </table>
     {% endfor %}
{% endif %}
{%endblock%}

forum_app/templates/forum/some_user_topics.html
{% extends 'main.html' %}
{% load tz %}

{% block title %}Мои темы{% endblock %}
{% block links %}
<link rel="stylesheet" href="{{MEDIA_URL}}f.css">
{%endblock%}

{% block mytopics %}active{% endblock %}
{% block forum %}active{% endblock %}

{% block body %}
<br>
<h2 class="indent" style="color:rgb(179, 179, 179);">Ваши темы.</h2>
{% if search_keys %}
<h6 class="indent text-white">Найдено: {{ all_topics_count }}</h6>
{% else %}
<h6 class="indent text-white">Всего: {{ all_topics_count }}</h6>
{% endif %}
{% if all_topics|length > 0 %}
     <table class="table border-success table-bordered table-dark table-striped" style="margin-left: 1%; width:98%">
         <thead>
             <tr>
                 <th scope="col" style="width:60%; margin:auto;">Название</th>
                 <th scope="col" style="width:15%; text-align: center;"><span style="font-size:15px;">Время добавления</span></th>
                 <th scope="col" style="width:5%; text-align: center;"><span style="font-size:12.5px;">Просмотры</span></th>
                 <th scope="col" style="width:20%; text-align: center;">Автор</th>
             </tr>
         </thead>
         <tbody>
             {% for topic in all_topics %}
                 <tr>
                 <td>
                     <a href="{{topic.obj.get_absolute_url}}" class="alert-link"><h5 class="indent" style="line-height: 10px">{{ topic.obj.title }}
                     <span style="float:right; font-size: 15px; color:rgb(128,128,128);">
                         в {{topic.section}}
                     </span>
                     </h5></a>
                 </td>
                 <td>
                     <p style="text-align: center; line-height: 10px">
                         {% if tzone %}
                            {% if tzone != 'Default' %}
                                {{topic.obj.time_added|timezone:tzone|date:"H:i, d/m/Y"}}
                            {% else %}
                                {{topic.obj.time_added|date:"H:i, d/m/Y"}}
                            {% endif %}
                        {% else %}
                            {{topic.obj.time_added|date:"H:i, d/m/Y"}}
                        {% endif %}
                     </p>
                 </td>
                 <td>
                     <p style="line-height: 10px; text-align: center;">{{topic.obj.views}}</p>
                 </td>
                 <td>
                     <p style="text-align: center; line-height: 10px"><a href="{% url 'home_app:some_user' topic.obj.author.username %}">{{topic.obj.author.username}}</a></p>
                 </td>
             </tr>
             {% endfor %}
         </tbody>
     </table>
{% else %}
     <h3 class="indent text-white">Темы не найдены.</h3>
{% endif %}
{%endblock%}