apiv1/urls.py
from django.urls import include, path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView
from rest_framework.routers import SimpleRouter

from apiv1.api_views import (
    AddCommentApiView,
    DislikeAPIView,
    DropAPIView,
    GetSectionsAPIView,
    GetSectionTopicsAPIView,
    GetTopicCommentsAPIView,
    GetUserAPIView,
    LikeAPIView,
    TopicViewSet,
    UpdateSettingsApiView,
)

router = SimpleRouter()
router.register(r"topics", TopicViewSet, basename="topics")

# domain.com/api/v1/
urlpatterns = [
    path("", include(router.urls)),
    path("topics/<int:ids>/comments/", GetTopicCommentsAPIView.as_view()),
    path("addcomment/", AddCommentApiView.as_view()),
    #
    path("sections/", GetSectionsAPIView.as_view()),
    path("sections/<str:section>/", GetSectionTopicsAPIView.as_view()),
    #
    path("user/<int:ids>/", GetUserAPIView.as_view()),
    path("reviewuser/like/<int:ids>/", LikeAPIView.as_view()),
    path("reviewuser/dislike/<int:ids>/", DislikeAPIView.as_view()),
    path("reviewuser/drop/<int:ids>/", DropAPIView.as_view()),
    path("updatesettings/", UpdateSettingsApiView.as_view()),
    #
    path("schema/", SpectacularAPIView.as_view(), name="schema"),
    path("schema/docs/", SpectacularSwaggerView.as_view(url_name="schema"))
]

forum/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path, re_path

from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("forum/", include("forum_app.urls")),
    path("", include("home_app.urls")),
    path("api/v1/", include("apiv1.urls")),
    re_path(r"^authorization/", include("djoser.urls.authtoken"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

forum_app/urls.py
from django.urls import path

from forum_app import views

app_name = "forum_app"

# domain.com/forum/
urlpatterns = [
    path("", views.forum_home_view, name="home"),
    path("add-topic/", views.AddTopicView.as_view(), name="add_topic"),
    path("my-topics/", views.SomeUserTopicsView.as_view(), name="my_topics"),
    path("search/", views.search_view, name="search"),
    path("<str:section>/", views.some_section_view, name="some_section"),
    path("<str:section>/<int:ids>/", views.some_id_view, name="some_id"),
    path("<str:section>/<int:ids>/add-comment/", views.AddCommentView.as_view(), name="add_comment"),
    path("<str:section>/<int:ids>/delete/", views.DeleteTopicView.as_view(), name="delete_topic"),
]

home_app/urls.py
from django.urls import path

from home_app import views

app_name = "home_app"

# domain.com/
urlpatterns = [
    path("", views.home_view, name="home"),
    path("auth/", views.AuthView.as_view(), name="auth"),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("logout/", views.LogoutView.as_view(), name="logout"),
    path("settings/", views.SettingsView.as_view(), name="settings"),
    path("account/<str:username>/", views.SomeUserView.as_view(), name="some_user"),
    path("account/like/<str:username>/", views.LikeView.as_view(), name="like"),
    path("account/dislike/<str:username>/", views.DislikeView.as_view(), name="dislike"),
    path("account/drop-review/<str:username>/", views.DropView.as_view(), name="drop")
]

templates/main.html
{% load tz %}

<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <title>{% block title %}{% endblock %}</title>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
     <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
     {% block links %}
     {%endblock%}
</head>
<body style="background-color: rgb(33, 33, 33);">
<div>
     <nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
         <div class="container-fluid">
             <a class="navbar-brand {% block home %} {% endblock %}" aria-current="page" href="{% url 'home_app:home' %}">
                 <img src="{{MEDIA_URL}}nanana.jpg" alt="madxlyeternity" width="40" height="40"> <!-- 3k pp -->
             </a>
             <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label ="Toggle navigation">
                 <span class="navbar-toggler-icon"></span>
             </button>
             <div class="collapse navbar-collapse" id="navbarNav">
                 <ul class="navbar-nav">
                     <li class="nav-item hv" style="margin-left: 8px;">
                         <a class="nav-link {% block forum %} {% endblock %}" aria-current="page" href="{% url 'forum_app:home' %}">Django Форум</a>
                     </li>
                     {% if request.user.is_authenticated %}
                         <li class="nav-item hv" style="margin-left: 15px;">
                             <a class="nav-link {% block user %} {% endblock %}" href="{% url 'home_app:some_user' request.user.username %}">Моя страница</a>
                         </li>
                         <li class="nav-item hv" style="margin-left: 15px;">
                             <a class="nav-link {% block settings %} {% endblock %}" href="{% url 'home_app:settings' %}">Настройки</a>
                         </li>
                         <li class="nav-item hv" style="margin-left: 15px;">
                             <a class="nav-link btn btn-danger" href="{% url 'home_app:logout' %}">Выход</a>
                         </li>
                     {% else %}
                     <li class="nav-item hv" style="margin-left: 15px;">
                         <a class="nav-link {% block auth %} {% endblock %}" href="{% url 'home_app:auth' %}">Вход</a>
                     </li>
                     {% endif %}
                 </ul>
             </div>
         </div>
     </nav>
     <br>
     {% if view_forum_menu %}
         <nav class="navbar navbar-expand-lg mx-auto p-2" style="width: 80%; background-color: rgb(25, 25, 25); border-radius: 5px;" data-bs-theme="dark">
             <div class="container-fluid">
                 <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                     <div class="navbar-nav">
                         <a class="nav-link {% block add %} {% endblock %}" aria-current="page" href="{% url 'forum_app:add_topic' %}">Добавить тему</a>
                         <a class="nav-link {% block mytopics %} {% endblock %}" aria-current="page" href="{% url 'forum_app:my_topics' %}" style="margin-left: 15px" >
                             Мои темы
                         </a>
                         {% if view_add_comment_button %}
                             <span class="indent" style="margin-left: 15px">
                                 <a class="nav-link {% block add_comment %} {% endblock %}" aria-current="page" href="{% url 'forum_app:add_comment' section topic.obj.pk %}">
                                     Добавить комментарий
                                 </a>
                             </span>
                         {% endif %}
                         {% if view_delete_button %}
                             <a class="nav-link {% block delete %} {% endblock %} btn btn-danger" aria-current="page" href="{% url 'forum_app:delete_topic' section topic.obj.pk %}" style="margin-left: 15px">
                                 Удалить тему
                             </a>
                         {% endif %}
                         {% if view_search_form %}
                             <div style="float:right" class="indent">
                                 <form class="d-flex" method="get">
                                     <input class="form-control me-2" type="search" placeholder="Поиск" aria-label="Search" name="search" id="search">
                                     <button class="btn btn-outline-success" type="submit">Поиск</button><br><br>
                                     <input type="checkbox" class="btn-check" name="title" id="title" style="margin-left: 15px" {% if 'title' in search_keys %}checked{% endif %} autocomplete="off">
                                     <label class="btn btn-outline-secondary" for="title" style="margin-left: 15px">Название</label>
                                     <input type="checkbox" class="btn-check" name="question" id="question" style="margin-left: 15px" {% if 'question' in search_keys %}checked{% endif %} autocomplete="off">
                                     <label class="btn btn-outline-secondary" for="question" style="margin-left: 15px">Вопрос</label>
                                     <input type="checkbox" class="btn-check" name="username" id="username" style="margin-left: 15px" {% if 'author__username' in search_keys %}checked{% endif %} autocomplete="off">
                                     <label class="btn btn-outline-secondary" for="username" style="margin-left: 15px">Юзернэйм</label>
                                 </form>
                             </div>
                         {% elif search_home %}
                            <span class="indent" style="margin-left: 15px">
                                 <a class="nav-link" aria-current="page" href="{% url 'forum_app:search' %}">
                                     Поиск по форуму
                                 </a>
                             </span>
                         {% endif %}
                   </div></div>
            </div>
         </nav>
     {% endif %}
     {% block body %}
    {% endblock %}
    {% if offset_action %}
     <div style="text-align:center">
        {% if offset_params.offset_back.view_button %}
             <div style="display: inline-block;">
                 <form method="get" action="
                 {% if offset_action.offset_action_param1 and offset_action.offset_action_param2 %}
                    {% url offset_action.offset_action offset_action.offset_action_param1 offset_action.offset_action_param2 %}
                 {% elif offset_action.offset_action_param1 %}
                    {% url offset_action.offset_action offset_action.offset_action_param1 %}
                 {% else %}
                    {% url offset_action.offset_action %}
                 {% endif %}
                 ">
                     <input type="hidden" name="offset" value="{{offset_params.offset_back.offset}}">
                     {% if offset_params.search %}
                     <input type="hidden" name="search" value="{{offset_params.search}}">
                     {% endif %}"
                     <button class="btn btn-primary" type="submit">
                         Назад
                     </button>
                </form>
             </div>
        {% endif %}
        {% if offset_params.offset_next.view_button %}
             <div style="display: inline-block;">
                 <form method="get" action="
                 {% if offset_action.offset_action_param1 and offset_action.offset_action_param2 %}
                    {% url offset_action.offset_action offset_action.offset_action_param1 offset_action.offset_action_param2 %}
                 {% elif offset_action.offset_action_param1 %}
                    {% url offset_action.offset_action offset_action.offset_action_param1 %}
                 {% else %}
                    {% url offset_action.offset_action %}
                 {% endif %}
                 ">
                     <input type="hidden" name="offset" value="{{offset_params.offset_next.offset}}">
                     {% if offset_params.search %}
                     <input type="hidden" name="search" value="{{offset_params.search}}">
                     {% endif %}"
                     <button class="btn btn-primary" type="submit">
                         Вперед
                     </button>
                </form>
             </div>
        {% endif %}
    </div>
    {% endif %}
    {% if view_info_menu %}
    <hr style="color: green; margin-left: 1%; width:98%; margin-bottom: 0px;">
    <table class="table table-bordered border-light-subtle" style="margin-left: 1%; width:98%; margin-bottom: 0px;">
        <tbody>
        <tr>
            <td style="background-color: rgb(25,25,25);">
                <h5 class="text-white">Информация:</h5>
                <h6 class="text-white">Общее количество тем: {{total_topics}}</h6>
                <h6 class="text-white">Общее количество сообщений: {{total_messages}}</h6>
                <h6 class="text-white">Последний зарегестрировавшийся пользователь:
                    {% if last_joined %}
                        <a href="{% url 'home_app:some_user' last_joined.username %}">{{last_joined.username}}</a>
                        в
                            {% if tzone %}
                                {% if tzone != 'Default' %}
                                    {{last_joined.date_joined|timezone:tzone|date:"H:i, d/m/Y"}}
                                {% else %}
                                    {{last_joined.date_joined|date:"H:i, d/m/Y"}}
                                {% endif %}
                            {% else %}
                                {{last_joined.date_joined|date:"H:i, d/m/Y"}}
                            {% endif %}</h6>
                        {% timezone tzone %}
                        <h6 class="text-white">Текущее время: {% now "H:i, d/m/Y" %}</h6>
                        {% endtimezone %}
                    {% else %}
                        отсутствует
                    {% endif %}
            </td>
        </tr>
        </tbody>
    </table>
    {% endif %}
</div>
</body>
</html>